apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  path: "./kustomizations/postgres-operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-package-software-factory
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: softwarefactoryaddons
      name: postgres-operator
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
